import os
import google.generativeai as genai
from dotenv import load_dotenv
import pandas as pd
import time

load_dotenv()

# --- 1. CONFIGURAÇÃO E CARREGAMENTO ---
try:
    genai.configure(api_key=os.environ.get("GOOGLE_API_KEY"))
except:
    print("Erro: Verifique sua GOOGLE_API_KEY no arquivo .env")
    exit()

print("Carregando base unificada...")
# MUDANÇA 1: Nome do arquivo atualizado
df = pd.read_csv("resultado_normalizacao_ia_unificado.csv")

# --- 2. EXTRAÇÃO INTELIGENTE DE LISTAS (MUDANÇA CRÍTICA) ---

# A) Categorias (Agora a coluna se chama 'tipo_produto')
categorias_reais = sorted(df['tipo_produto'].dropna().unique())

# B) Marcas
marcas_reais = sorted(df['marca'].dropna().unique())

# C) Funções (Unifica Cabelo 'beneficio_principal' + Unha 'acabamento_efeito' + 'funcao_tratamento')
#    Isso cria uma lista mestre de termos técnicos para gerar sinônimos
lista_funcoes_bruta = (
    df['beneficio_principal'].fillna('').tolist() + 
    df['acabamento_efeito'].fillna('').tolist() +
    df['funcao_tratamento'].fillna('').tolist()
)
# Remove vazios e duplicatas
funcoes_reais = sorted(list(set([x for x in lista_funcoes_bruta if x != ''])))

# D) Unidades (Extração via Regex mantida)
unidades_reais = df['volume_peso'].astype(str).str.extract(r'([a-zA-Z]+)$')[0].dropna().unique().tolist()

# Preparando Strings para o Prompt
lista_categorias_str = "\n".join([f"- {cat}" for cat in categorias_reais])
lista_marcas_str = ", ".join(marcas_reais[:30]) # Top 30 para contexto negativo
lista_funcoes_str = ", ".join(funcoes_reais[:30]) # Top 30 para contexto

# --- 3. MONTAGEM DO SUPER PROMPT (DINÂMICO) ---
# O prompt é definido AQUI para pegar as variáveis carregadas acima
prompt_system = f"""
SYSTEM ROLE:
Você é um Especialista Sênior em Engenharia de Busca (Search Engineer) para E-commerce.
Sua missão é gerar um Synonym Map ("Expansion Synonyms") no formato Solr.

CONTEXTO DO CATÁLOGO (O QUE EXISTE NO BANCO):
---------------------------------------------------------
GRUPOS ALVO (LADO DIREITO DA SETA - CANÔNICOS):
{lista_categorias_str}

LISTA DE MARCAS (APENAS PARA PROTEÇÃO - NÃO GERAR SINÔNIMOS):
{lista_marcas_str}...

LISTA DE UNIDADES VÁLIDAS:
g, ml, kg, un, cm
---------------------------------------------------------

REGRAS DE OURO (HARD CONSTRAINTS):
1. SIGLAS TÉCNICAS: Mapeie siglas comuns (shp, cond, esm, tint) para suas Categorias.
2. ERROS DE GRAFIA: Mapeie erros fonéticos (xampu -> Shampoo, pincar -> Pinça).
3. UNIDADES: Padronize variações (gr, gramas -> g).
4. PROTEÇÃO DE MARCAS: JAMAIS coloque uma marca no lado esquerdo mapeando para uma categoria.
   - ERRO GRAVE: "risqué => Esmalte" (ISSO É PROIBIDO).
   - CORRETO: "esmalte risque => Esmalte" (Frase composta pode, marca sozinha não).

TAREFA:
Gere a lista completa de sinônimos para Categorias e Unidades.
Formato: termo_errado, giria, sigla => Termo_Canônico
"""

# --- 4. INSTANCIA O MODELO ---
model = genai.GenerativeModel(
    model_name='gemini-2.5-flash', 
    system_instruction=prompt_system, # Passamos o prompt montado aqui
    generation_config={
        "temperature": 0.3, # Baixa temperatura para precisão
        "response_mime_type": "text/plain"
    }
)

print("--- GERANDO ARQUIVO DE SINÔNIMOS (SOLR FORMAT) ---\n")

if os.path.exists("synonyms.txt"):
    os.remove("synonyms.txt")
    print("Arquivo synonyms.txt anterior removido.\n")

# --- 5. CHAMADA ÚNICA (MUDANÇA 3) ---
# Mandamos tudo de uma vez para garantir consistência e zero ambiguidade
try:
    print("Enviando solicitação ao Gemini...")
    
    msg_usuario = f"""
    Com base nas categorias acima, gere o Synonym Map completo.
    
    Foque nestes casos prioritários:
    1. Siglas de cadastro (SHP, COND, ESM, TINT).
    2. Variações de Unidades ({', '.join(unidades_reais)}).
    3. Erros de digitação comuns para: {', '.join(categorias_reais)}.
    """
    
    response = model.generate_content(msg_usuario)
    
    print("\n--- RESPOSTA GERADA ---")
    print(response.text[:500] + "... (troncado na tela)") 
    
    with open("synonyms.txt", "w", encoding="utf-8") as arquivo:
        arquivo.write("# --- SYNONYMS MAP GENERATED BY AI ---\n")
        arquivo.write(response.text)
        
    print(f"\n✅ Sucesso! Arquivo 'synonyms.txt' gerado.")

except Exception as e:
    print(f"❌ Erro na geração: {e}")